output "module_name" {
  description = "Name of the placeholder module."
  value       = local.module_name
}

output "labels" {
  description = "Local labels generated by the placeholder module."
  value       = local.labels
}
