{
 "title": "App Overview",
 "tags": [
  "week05",
  "observability",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "prometheus up"
    }
   ]
  },
  {
   "title": "Head Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "head series" }
   ]
  },
  {
   "title": "Config Reload Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful",
     "legendFormat": "config reload ok"
    }
   ]
  },
  {
   "title": "Prometheus HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[1m])",
     "legendFormat": "{{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Java Target Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"media-task-platform-java\"}",
     "legendFormat": "java up"
    }
   ]
  },
  {
   "title": "Java Hikari Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{job=\"media-task-platform-java\"}",
     "legendFormat": "hikari connections"
    }
   ]
  },
  {
   "title": "Java Ready Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{job=\"media-task-platform-java\"}",
     "legendFormat": "ready time"
    }
   ]
  }
 ]
}